from __future__ import print_function

"""
Plot in-vivo SSIM-DA curves and identify candidate checkpoints.

This script reads the outputs generated by calculate_ssim_da_in_vivo.py:

    epochs.npy
    ssim_da.npy
    ssim_da_channel_bvalues.npy

SSIM-DA definition:
    SSIM between reconstructed direction-averaged images and the
    corresponding noisy direction-averaged images, where diffusion
    directions are averaged separately within each b-value shell.
"""

from pathlib import Path

import matplotlib
matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
from matplotlib import font_manager
from matplotlib.ticker import MaxNLocator
from scipy.ndimage import median_filter


# =====================================================================
# 0. Plot style
# =====================================================================

available_fonts = {
    font.name
    for font in font_manager.fontManager.ttflist
}

if "Times New Roman" in available_fonts:
    MAIN_FONT = "Times New Roman"

elif "Liberation Serif" in available_fonts:
    MAIN_FONT = "Liberation Serif"

elif "Nimbus Roman" in available_fonts:
    MAIN_FONT = "Nimbus Roman"

else:
    MAIN_FONT = "DejaVu Serif"


print("Using font:", MAIN_FONT)


plt.rcParams["font.family"] = "serif"
plt.rcParams["font.serif"] = [MAIN_FONT]
plt.rcParams["mathtext.fontset"] = "stix"
plt.rcParams["axes.unicode_minus"] = False

plt.rcParams["font.size"] = 18
plt.rcParams["axes.titlesize"] = 18
plt.rcParams["axes.labelsize"] = 18
plt.rcParams["xtick.labelsize"] = 18
plt.rcParams["ytick.labelsize"] = 18
plt.rcParams["legend.fontsize"] = 12


# =====================================================================
# 1. Configuration
# =====================================================================

# Must be the same SAVE_DIR used by the SSIM-DA calculation script.
METRIC_DIR = Path(
    "/root/xje/DIP_M2_W_3D/mgh_hcp2/"
    "offline_metrics_in_vivo_ssim_da"
)


SAVE_FIG_DIR = (
    METRIC_DIR
    / "curve_figures_ssim_da_median_max"
)


# ---------------------------------------------------------------------
# Optional displayed iteration range
# ---------------------------------------------------------------------

START_ITERATION = None
END_ITERATION = None


# Plot display range only.
# It does NOT affect checkpoint selection.
PLOT_XLIM = (
    0,
    50000,
)


# Set None for automatic y-axis limits.
SSIM_YLIM = None


# ---------------------------------------------------------------------
# X-axis
# ---------------------------------------------------------------------

# Display:
#
# 0, 1, 2, 3, 4, 5
#
# with ×10^4.
ITERATION_TICK_STEP = 10000
ITERATION_AXIS_SCALE = 10000
SHOW_ITERATION_POWER_LABEL = True


# ---------------------------------------------------------------------
# Figure
# ---------------------------------------------------------------------

FIG_DPI = 600
FIG_CREATE_DPI = 600
FIG_FORMAT = "png"

FIG_SIZE = (
    6.6,
    6.0,
)

LINE_WIDTH = 2.0
MAX_MAJOR_TICKS = 5


# ---------------------------------------------------------------------
# Colors
# ---------------------------------------------------------------------

SSIM_RAW_COLOR = "tab:orange"
SSIM_FILTERED_COLOR = "tab:orange"

LIMITED_SSIM_COLOR = "blue"
GLOBAL_SSIM_COLOR = "gold"

POINT_EDGE_COLOR = "black"


# ---------------------------------------------------------------------
# SSIM-DA labels
# ---------------------------------------------------------------------

TITLE_TEXT = "SSIM-DA"
Y_AXIS_LABEL = "SSIM-DA"

LEGEND_LOCATION = "center right"


# ---------------------------------------------------------------------
# File names
# ---------------------------------------------------------------------

SSIM_KEY = "ssim_da"
SSIM_FILTERED_KEY = "ssim_da_median"


# ---------------------------------------------------------------------
# Median filtering
# ---------------------------------------------------------------------

# Must be a positive odd integer.
#
# If checkpoints are saved every 40 iterations:
#
# window = 11
#
# spans approximately 400 iterations.
SSIM_MEDIAN_WINDOW = 11

PLOT_MEDIAN_FILTERED_SSIM = True


# ---------------------------------------------------------------------
# Checkpoint selection intervals
# ---------------------------------------------------------------------

# Blue point:
# maximum median-filtered SSIM-DA before 20000.
LIMITED_SSIM_SELECTION_START_ITERATION = 0
LIMITED_SSIM_SELECTION_END_ITERATION = 20000


# Yellow point:
# maximum median-filtered SSIM-DA over the full range.
GLOBAL_SSIM_SELECTION_START_ITERATION = 0
GLOBAL_SSIM_SELECTION_END_ITERATION = 50000


LIMITED_SSIM_SELECTION_SAVE_DIR = (
    SAVE_FIG_DIR
    / "ssim_da_max_before_end_selection"
)

GLOBAL_SSIM_SELECTION_SAVE_DIR = (
    SAVE_FIG_DIR
    / "ssim_da_global_max_selection"
)


# =====================================================================
# 2. Load arrays
# =====================================================================

def load_array(
    path: Path,
    dtype=np.float64,
):

    if not path.exists():
        raise FileNotFoundError(
            f"Missing required metric file: {path}"
        )

    values = np.load(
        path,
        allow_pickle=False,
    )

    return np.asarray(
        values,
        dtype=dtype,
    ).reshape(-1)


# =====================================================================
# 3. Median filter
# =====================================================================

def median_filter_1d(
    values,
    window_size,
):

    values = np.asarray(
        values,
        dtype=np.float64,
    ).reshape(-1)

    if (
        window_size < 1
        or window_size % 2 == 0
    ):
        raise ValueError(
            "SSIM_MEDIAN_WINDOW must be a "
            "positive odd integer."
        )

    if not np.all(
        np.isfinite(values)
    ):
        raise ValueError(
            "SSIM-DA contains NaN or infinite values."
        )

    return median_filter(
        values,
        size=window_size,
        mode="nearest",
    )


# =====================================================================
# 4. Select maximum median-filtered SSIM-DA
# =====================================================================

def select_median_filtered_max(
    iterations,
    raw_values,
    start_iteration,
    end_iteration,
    metric_name,
):
    """
    Select the maximum median-filtered SSIM-DA
    inside the requested interval.

    Filtering is performed independently inside
    each selection interval.
    """

    iterations = np.asarray(
        iterations,
        dtype=np.int64,
    ).reshape(-1)

    raw_values = np.asarray(
        raw_values,
        dtype=np.float64,
    ).reshape(-1)

    if len(iterations) != len(raw_values):
        raise ValueError(
            f"{metric_name}: iterations and values "
            "have different lengths."
        )

    if (
        end_iteration is not None
        and end_iteration < start_iteration
    ):
        raise ValueError(
            f"{metric_name}: end iteration must "
            "be >= start iteration."
        )


    valid = (
        (iterations >= start_iteration)
        & np.isfinite(raw_values)
    )

    if end_iteration is not None:
        valid &= (
            iterations <= end_iteration
        )


    valid_indices = np.flatnonzero(
        valid
    )

    if valid_indices.size == 0:
        raise ValueError(
            f"No valid {metric_name} values "
            f"in interval "
            f"[{start_iteration}, {end_iteration}]."
        )


    interval_raw = (
        raw_values[valid_indices]
    )


    interval_filtered = (
        median_filter_1d(
            interval_raw,
            SSIM_MEDIAN_WINDOW,
        )
    )


    selected_local_index = int(
        np.argmax(
            interval_filtered
        )
    )


    selected_index = int(
        valid_indices[
            selected_local_index
        ]
    )


    return {

        "selected_index":
            selected_index,

        "selected_iteration":
            int(
                iterations[
                    selected_index
                ]
            ),

        "selected_raw_ssim_da":
            float(
                raw_values[
                    selected_index
                ]
            ),

        "selected_filtered_ssim_da":
            float(
                interval_filtered[
                    selected_local_index
                ]
            ),

        "selection_start_iteration":
            int(
                start_iteration
            ),

        "selection_end_iteration":
            (
                None
                if end_iteration is None
                else int(
                    end_iteration
                )
            ),
    }


# =====================================================================
# 5. Restrict display range
# =====================================================================

def restrict_iteration_range(
    iterations,
    arrays,
):

    keep = np.ones(
        len(iterations),
        dtype=bool,
    )


    if START_ITERATION is not None:

        keep &= (
            iterations
            >= START_ITERATION
        )


    if END_ITERATION is not None:

        keep &= (
            iterations
            <= END_ITERATION
        )


    if not np.any(keep):

        raise ValueError(
            "No data remain after applying "
            "the iteration range."
        )


    return (

        iterations[keep],

        {
            name:
                np.asarray(values)[keep]

            for name, values
            in arrays.items()
        },
    )


# =====================================================================
# 6. Helpers
# =====================================================================

def format_interval(
    start_iteration,
    end_iteration,
):

    end_text = (
        "end"
        if end_iteration is None
        else str(end_iteration)
    )

    return (
        f"{start_iteration}-{end_text}"
    )


def build_point(
    selection,
    label,
    color,
    size,
    zorder,
):

    return {

        "label":
            label,

        "iteration":
            selection[
                "selected_iteration"
            ],

        "raw_ssim_da":
            selection[
                "selected_raw_ssim_da"
            ],

        "filtered_ssim_da":
            selection[
                "selected_filtered_ssim_da"
            ],

        "start_iteration":
            selection[
                "selection_start_iteration"
            ],

        "end_iteration":
            selection[
                "selection_end_iteration"
            ],

        "color":
            color,

        "size":
            size,

        "zorder":
            zorder,
    }


def mark_point(
    ax,
    point,
):

    ax.scatter(

        [
            point[
                "iteration"
            ]
        ],

        [
            point[
                "filtered_ssim_da"
            ]
        ],

        s=point["size"],

        marker="o",

        facecolor=point["color"],

        edgecolor=POINT_EDGE_COLOR,

        linewidth=0.8,

        zorder=point["zorder"],

        label=point["label"],
    )


# =====================================================================
# 7. Save selected checkpoints
# =====================================================================

def save_selection(
    save_dir,
    point,
):

    save_dir.mkdir(
        parents=True,
        exist_ok=True,
    )


    selected = np.asarray(
        [
            point[
                "iteration"
            ]
        ],
        dtype=np.int64,
    )


    np.save(
        save_dir
        / "selected_iteration.npy",
        selected,
    )

    np.save(
        save_dir
        / "selected_epoch.npy",
        selected,
    )


    lines = [

        f"Selection name = "
        f"{point['label']}",

        f"Selection interval = "
        f"[{point['start_iteration']}, "
        f"{point['end_iteration']}]",

        f"SSIM-DA median window = "
        f"{SSIM_MEDIAN_WINDOW}",

        "",

        f"Selected Iteration = "
        f"{point['iteration']}",

        f"Original SSIM-DA = "
        f"{point['raw_ssim_da']:.12g}",

        f"Median-filtered SSIM-DA = "
        f"{point['filtered_ssim_da']:.12g}",

        "",

        "Selection rule:",

        "Apply one median filter to SSIM-DA "
        "inside the configured interval and "
        "select the maximum of the filtered curve.",
    ]


    summary_path = (
        save_dir
        / "selection_summary.txt"
    )


    summary_path.write_text(
        "\n".join(lines) + "\n",
        encoding="utf-8",
    )


    print(
        f"[Saved] {summary_path}"
    )


# =====================================================================
# 8. X-axis formatting
# =====================================================================

def apply_iteration_axis(ax):

    """
    Format iterations as:

        0, 1, 2, ...

    with a ×10^4 multiplier.
    """

    if PLOT_XLIM is not None:

        xmin, xmax = (
            PLOT_XLIM
        )

        ax.set_xlim(
            xmin,
            xmax,
        )

    else:

        xmin, xmax = (
            ax.get_xlim()
        )


    first_tick = int(
        np.ceil(
            xmin
            / ITERATION_TICK_STEP
        )
        * ITERATION_TICK_STEP
    )


    last_tick = int(
        np.floor(
            xmax
            / ITERATION_TICK_STEP
        )
        * ITERATION_TICK_STEP
    )


    ticks = np.arange(
        first_tick,
        last_tick
        + ITERATION_TICK_STEP,
        ITERATION_TICK_STEP,
        dtype=np.int64,
    )


    if ticks.size > 0:

        ax.set_xticks(
            ticks
        )

        ax.set_xticklabels(
            [
                f"{tick / ITERATION_AXIS_SCALE:g}"
                for tick in ticks
            ]
        )

    else:

        ax.xaxis.set_major_locator(
            MaxNLocator(
                nbins=MAX_MAJOR_TICKS
            )
        )


    if SHOW_ITERATION_POWER_LABEL:

        ax.text(
            1.0,
            -0.115,
            r"$\times10^{4}$",

            transform=ax.transAxes,

            ha="right",
            va="top",

            fontsize=16,
        )


# =====================================================================
# 9. Figure formatting
# =====================================================================

def finish_axis(
    ax,
    title,
    ylabel,
):

    ax.set_title(
        title
    )

    ax.set_xlabel(
        "Iteration"
    )

    ax.set_ylabel(
        ylabel,
        color=SSIM_FILTERED_COLOR,
    )

    ax.grid(False)


    apply_iteration_axis(
        ax
    )


    if SSIM_YLIM is not None:

        ax.set_ylim(
            SSIM_YLIM[0],
            SSIM_YLIM[1],
        )


    ax.yaxis.set_major_locator(
        MaxNLocator(
            nbins=MAX_MAJOR_TICKS
        )
    )


    ax.tick_params(
        axis="x",
        direction="out",
        length=4,
        width=1,
        colors="black",
    )


    ax.tick_params(
        axis="y",
        direction="out",
        length=4,
        width=1,
        colors=SSIM_FILTERED_COLOR,
    )


    ax.spines[
        "left"
    ].set_color(
        "black"
    )

    ax.spines[
        "right"
    ].set_color(
        "black"
    )

    ax.spines[
        "top"
    ].set_color(
        "black"
    )

    ax.spines[
        "bottom"
    ].set_color(
        "black"
    )


    handles, labels = (
        ax.get_legend_handles_labels()
    )


    if handles:

        ax.legend(
            frameon=False,
            fontsize=10,
            loc=LEGEND_LOCATION,
        )


def save_figure(
    fig,
    filename,
):

    SAVE_FIG_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )


    save_path = (
        SAVE_FIG_DIR
        / f"{filename}.{FIG_FORMAT}"
    )


    fig.tight_layout()

    fig.subplots_adjust(
        bottom=0.18
    )


    fig.savefig(
        save_path,
        dpi=FIG_DPI,
        bbox_inches="tight",
    )


    plt.close(
        fig
    )


    print(
        f"[Saved] {save_path}"
    )


# =====================================================================
# 10. Main
# =====================================================================

def main():

    SAVE_FIG_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )


    # -------------------------------------------------------------
    # Load SSIM-DA calculation results
    # -------------------------------------------------------------

    iterations_full = load_array(
        METRIC_DIR
        / "epochs.npy",
        dtype=np.int64,
    )


    raw_ssim_da_full = load_array(
        METRIC_DIR
        / "ssim_da.npy",
    )


    if len(iterations_full) == 0:

        raise ValueError(
            "epochs.npy is empty."
        )


    if (
        len(raw_ssim_da_full)
        != len(iterations_full)
    ):

        raise ValueError(
            "ssim_da.npy and epochs.npy "
            "have different lengths."
        )


    if np.any(
        np.diff(
            iterations_full
        ) <= 0
    ):

        raise ValueError(
            "epochs.npy must be "
            "strictly increasing."
        )


    print(
        "Loaded iterations :",
        len(iterations_full),
    )


    print(
        "SSIM-DA range     : "
        f"[{np.min(raw_ssim_da_full):.6f}, "
        f"{np.max(raw_ssim_da_full):.6f}]"
    )


    # -------------------------------------------------------------
    # Median-filtered SSIM-DA
    # -------------------------------------------------------------

    filtered_ssim_da_full = (
        median_filter_1d(
            raw_ssim_da_full,
            SSIM_MEDIAN_WINDOW,
        )
    )


    np.save(
        SAVE_FIG_DIR
        / f"{SSIM_FILTERED_KEY}.npy",

        filtered_ssim_da_full,
    )


    # -------------------------------------------------------------
    # Select maximum before 20000
    # -------------------------------------------------------------

    limited_selection = (
        select_median_filtered_max(

            iterations_full,

            raw_ssim_da_full,

            LIMITED_SSIM_SELECTION_START_ITERATION,

            LIMITED_SSIM_SELECTION_END_ITERATION,

            "limited-interval SSIM-DA",
        )
    )


    # -------------------------------------------------------------
    # Select global maximum
    # -------------------------------------------------------------

    global_selection = (
        select_median_filtered_max(

            iterations_full,

            raw_ssim_da_full,

            GLOBAL_SSIM_SELECTION_START_ITERATION,

            GLOBAL_SSIM_SELECTION_END_ITERATION,

            "global SSIM-DA",
        )
    )


    limited_interval_text = (
        format_interval(

            LIMITED_SSIM_SELECTION_START_ITERATION,

            LIMITED_SSIM_SELECTION_END_ITERATION,
        )
    )


    global_interval_text = (
        format_interval(

            GLOBAL_SSIM_SELECTION_START_ITERATION,

            GLOBAL_SSIM_SELECTION_END_ITERATION,
        )
    )


    # -------------------------------------------------------------
    # Points
    # -------------------------------------------------------------

    limited_point = build_point(

        limited_selection,

        label=(
            "SSIM-DA selection "
            f"({limited_interval_text})"
        ),

        color=LIMITED_SSIM_COLOR,

        size=85,

        zorder=9,
    )


    global_point = build_point(

        global_selection,

        label=(
            "SSIM-DA selection "
            f"({global_interval_text})"
        ),

        color=GLOBAL_SSIM_COLOR,

        size=70,

        zorder=10,
    )


    save_selection(
        LIMITED_SSIM_SELECTION_SAVE_DIR,
        limited_point,
    )


    save_selection(
        GLOBAL_SSIM_SELECTION_SAVE_DIR,
        global_point,
    )


    # -------------------------------------------------------------
    # Restrict plotting range
    # -------------------------------------------------------------

    iterations, arrays = (
        restrict_iteration_range(

            iterations_full,

            {
                SSIM_KEY:
                    raw_ssim_da_full,

                SSIM_FILTERED_KEY:
                    filtered_ssim_da_full,
            },
        )
    )


    # -------------------------------------------------------------
    # Plot
    # -------------------------------------------------------------

    fig, ax = plt.subplots(

        figsize=FIG_SIZE,

        dpi=FIG_CREATE_DPI,
    )


    # Raw SSIM-DA
    ax.plot(

        iterations,

        arrays[
            SSIM_KEY
        ],

        linewidth=1.0,

        color=SSIM_RAW_COLOR,

        alpha=0.45,

        label="Original SSIM-DA",
    )


    # Median-filtered SSIM-DA
    if PLOT_MEDIAN_FILTERED_SSIM:

        ax.plot(

            iterations,

            arrays[
                SSIM_FILTERED_KEY
            ],

            linewidth=LINE_WIDTH,

            color=SSIM_FILTERED_COLOR,

            label=(
                "Median-filtered SSIM-DA"
            ),
        )


    # Selection points
    mark_point(
        ax,
        limited_point,
    )

    mark_point(
        ax,
        global_point,
    )


    finish_axis(
        ax,
        TITLE_TEXT,
        Y_AXIS_LABEL,
    )


    save_figure(
        fig,
        "01_SSIM_DA",
    )


    # -------------------------------------------------------------
    # Print
    # -------------------------------------------------------------

    print(
        "\n"
        "================ "
        "In-vivo SSIM-DA selection "
        "================"
    )


    for point in (
        limited_point,
        global_point,
    ):

        print(
            f"\n{point['label']}"
        )

        print(
            f"  Iteration: "
            f"{point['iteration']}"
        )

        print(
            f"  Original SSIM-DA: "
            f"{point['raw_ssim_da']:.10g}"
        )

        print(
            f"  Median-filtered SSIM-DA: "
            f"{point['filtered_ssim_da']:.10g}"
        )


    if (
        limited_point[
            "iteration"
        ]
        ==
        global_point[
            "iteration"
        ]
    ):

        print(
            "\n[Notice] "
            "The blue and yellow points "
            "occur at the same iteration."
        )


    print(
        "\nFigure saved to:"
    )

    print(
        SAVE_FIG_DIR
        / f"01_SSIM_DA.{FIG_FORMAT}"
    )


if __name__ == "__main__":
    main()
